import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import FooterSection from "@/components/FooterSection";

const inter = Inter({ subsets: ["greek", "cyrillic", "cyrillic-ext", "latin", "latin-ext", "vietnamese"] });

export const metadata: Metadata = {
  title: "COTE (Center Of Technology Evolution)",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <FooterSection />
    </html>
  );
}
