// import AdvocacyResearchSection from "@/components/AdvocancyComponent";
// import ArticleComponents from "@/components/ArticleComponents";
import Partners from "@/components/ClientsComponents";
import DataProtectionAwareness from "@/components/DataProtectionAwareness";
import DigitalInclusionSection from "@/components/DigitalInclusionComponent";
import DrivingChangeComponent from "@/components/DrivingChangeComponent";
import HeaderSection from "@/components/HeaderSection";
import InternetFreedomAwareness from "@/components/InternetFredomAwareness";
// import LegalAidComponent from "@/components/LegalAidcomponent";
import NewsletterSignup from "@/components/NewsComponent";
import SubscriptionComponent from "@/components/SubscribeComponent";
import { Metadata } from "next/types";
import React from "react";
export const metadata: Metadata = {
  title: "COTE | Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="mx-auto">
      <HeaderSection />
      <NewsletterSignup />
      <DataProtectionAwareness />
      <InternetFreedomAwareness />
      <DrivingChangeComponent />
      <DigitalInclusionSection />
      {/* <AdvocacyResearchSection /> */}
      {/* <LegalAidComponent /> */}
      <SubscriptionComponent />
      {/* <ArticleComponents /> */}
      <Partners />
    </main>
  );
}
